config/routes.rb
Bitpages::Application.routes.draw do
  
  mount Messaging::Engine => "/messaging"
  devise_for :messaging_users
  devise_for :admin_users, ActiveAdmin::Devise.config

  authenticated :user do
    root :to => "dashboard#index"
  end

  authenticated :merchant do
    root :to => "dashboard#index"
  end

  authenticated :merchant_profile do
    root :to => "dashboard#index"
  end

  root :to => "home#index"

  devise_for :merchants
  devise_for :users, :controllers => {:registrations => "user_registrations"}
  devise_for :merchant_profiles, :controllers => { :registrations => "merchant_profiles" }

  resources :profile

  resources :merchant_profiles
  
  resources :merchants
  resources :merchant_friendships
  resources :merchant_user_friendships

  resources :users
  resources :user_friendships
  resources :user_merchant_friendships

  match '/map', :to => "dashboard#map"
  match '/search', :to => "dashboard#search"
  match '/network', :to => "dashboard#network"

  match '/about', :to => "home#about"
  match '/contact', :to => "home#contact"
  match '/help', :to => "home#help"

  resources :user_submissions
  
  resources :messages

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
      delete :destroy_trash
    end
  end

  ActiveAdmin.routes(self)
    namespace :admin do
      resources :users do
        resources :messages
      end
      resources :merchant_profiles do
        resources :messages
      end
    end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  include DashboardHelper
  def index
    @merchants = Merchant.latest.paginate(:page => params[:merchant_page], :per_page => 5)
    @new_members = User.latest.paginate(:page => params[:user_page], :per_page => 3)

    if current_merchant_profile.present?
      gon.current_user = current_merchant_profile
      @number_of_friendships = Merchant.number_of_friendships(current_merchant_profile.merchant).to_s
    elsif current_user.present?
      gon.current_user = current_user
      @number_of_friendships = User.number_of_friendships(current_user)
    end
  end

  def map
    # if params[:category].blank?
    #   redirect_to root_url and return
    # end

    set_current_user
    if current_merchant_profile.present?
      gon.current_user = current_merchant_profile
      @number_of_friendships = Merchant.number_of_friendships(current_merchant_profile.merchant).to_s
    elsif current_user.present?
      gon.current_user = current_user
      @number_of_friendships = User.number_of_friendships(current_user)
    end

    if params[:user_search_link]
      @merchants = Merchant.last(4).reverse
      @new_members = User.alphabetically
      render "search" and return
    elsif params[:user_search_button]
      @merchants = Merchant.last(4).reverse
      @new_members = User.alphabetically.where("name ILIKE?", "%"+"#{params[:user_name]}"+"%")
      render "search" and return
    elsif !params[:zip_code].present? && params[:category].present? && params[:submit_search]
      @merchants = Merchant.alphabetically.where("industry ILIKE?", "%"+"#{params[:category]}"+"%")
      gon.merchants = @merchants
      @new_members = User.last(3).reverse
      render "search" and return
    elsif !params[:zip_code].present? && !params[:category].present? && params[:submit_search]
      @merchants = Merchant.alphabetically
      @new_members = User.last(3).reverse
      render "search" and return
    elsif !valid_zipcode?(params[:zip_code])
      flash.alert = "Invalid Zip Code."
      redirect_to root_url and return
    else
      set_zip_code_and_industry
      begin
        if gon.industry.present?
          merchant_industry_array = Merchant.alphabetically.where("industry ILIKE?", "%"+"#{gon.industry}"+"%")
          @merchants = merchant_industry_array.within(10, :origin => gon.zip_code)
          @new_members = User.last(3).reverse
        else
          @merchants = Merchant.within(10, :origin => gon.zip_code)
        end
      rescue Geokit::Geocoders::GeocodeError
        flash.alert = "Invalid Zip Code."
        redirect_to root_url and return
      end

      if @merchants.present? && !@merchants.empty?
        if params[:merchant_map]
          gon.center = Geocoder::Calculations.geographic_center(@merchants)
        elsif params[:submit_search]
          @new_members = User.last(3).reverse
          gon.merchants = @merchants

          if current_merchant_profile.present? == false && current_user.present? == false
            gon.center = Geocoder::Calculations.geographic_center(@merchants)
            render "unregistered_search" and return
          else
            render "search" and return
          end
        end
      else
        flash.alert = "No matches found."
        redirect_to root_url and return
      end
      gon.merchants = @merchants
    end

  end

  def network
    set_current_user
    set_current_user_followers(@user)
  end

  def search
    if current_merchant_profile.present?
      gon.current_user = current_merchant_profile
      @number_of_friendships = Merchant.number_of_friendships(current_merchant_profile.merchant).to_s
    elsif current_user.present?
      gon.current_user = current_user
      @number_of_friendships = User.number_of_friendships(current_user)
    end
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper

  def valid_zipcode?(zip_code)
    return false if zip_code.blank?
    zip_code.to_s
    if zip_code.length == 5 && zip_code.to_i != 0 && zip_code.to_i.to_s.length >= 4
      true
    else
      false
    end
  end

  def set_current_user
    if current_merchant_profile.present?
      gon.current_user = current_merchant_profile
      @user = current_merchant_profile.merchant
    elsif current_user.present?
      gon.current_user = current_user
      @user = current_user
    end
  end

  def set_current_user_followers(current_account)
    if current_account.class == Merchant
      @merchant_followers = MerchantFriendship.where(:merchant_friend_id => current_account.id)
      @user_followers = UserMerchantFriendship.where(:merchant_id => current_account.id)
    elsif current_account.class == User
      @user_followers = UserFriendship.where(:user_friend_id => current_account.id)
      @merchant_followers = MerchantUserFriendship.where(:user_id => current_account.id )
    end
  end

  def set_zip_code_and_industry
    if params[:zip_code] && params[:zip_code].first == "0"
      gon.zip_code = Geocoder.coordinates(params[:zip_code])
    else
      gon.zip_code = params[:zip_code]
    end
    gon.industry = params[:category]
  end
end

app/views/dashboard/_discover_users.html.erb
<div class="row">
  <div class="span9 search">
    <h4>DISCOVER BITCOIN USERS</h4>
    <%= form_tag map_path, :method => 'post' do %>
      <%= text_field_tag :user_name, nil, :placeholder => "Search username" %> <br />
      <%= button_tag "Search", :name => "user_search_button", :style => "width: 220px;", :class => "btn btn-primary" %><br>
      <%= button_tag "Search for All Users", :name => "user_search_link", :id => "user-search" %>
    <% end %>
  </div>
</div>

app/views/dashboard/_individual_network.html.erb
<div class="network">
  <h2><%= current_user.name %>'s network </h2> <p><%= button_to "Back to Dashboard", root_path %></p>
  <div class="row">
    <div class="span12 follows">
      <h4>Accounts you are following: </h4>
    </div>
    <div class="span5">
      <h4>Merchants</h4>
      <% @user.user_merchant_friendships.each do |user_merchant_friendship| %>
        <% next if user_merchant_friendship.blank? || user_merchant_friendship.merchant.blank? %>
        <div class="row">
          <div class="span5 recent-merchants-dashboard">
            <p style="margin-left:30px; margin-bottom: 0;">
              <%= user_merchant_friendship.merchant.bname %> (<%= link_to "remove friend", user_merchant_friendship, :method => :delete %>)
            </p>

            <div class="each-merchant" style="margin-left:30px;">
              <div class="row">
                <div class="span1">
                  <% if user_merchant_friendship.merchant.merchant_profile && user_merchant_friendship.merchant.merchant_profile.approved %>
                    <%= link_to image_tag(user_merchant_friendship.merchant.merchant_profile.avatar.url), user_merchant_friendship.merchant %>
                  <% else %>
                   <%= link_to image_tag(user_merchant_friendship.merchant.avatar.url), user_merchant_friendship.merchant %>

                  <% end %>
                </div>

                <div class="span1 bname">
                  <h5><%= link_to user_merchant_friendship.merchant.bname, user_merchant_friendship.merchant %></h5>
                  <p><%= user_merchant_friendship.merchant.industry %></p>
                </div>

                <div class="span2 address" >
                  <% if user_merchant_friendship.merchant.street_address %>
                    <p><%= user_merchant_friendship.merchant.street_address %></p>
                    <p><%= user_merchant_friendship.merchant.city %>, <%= user_merchant_friendship.merchant.state %> <%= user_merchant_friendship.merchant.zip_code %></p>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div class="span3 recent-users-dashboard">
      <h4>People</h4>
      <% @user.user_friendships.each do |user_friendship| %>
        <% next if user_friendship.blank? || user_friendship.user_friend.blank? %>
         <%= user_friendship.user_friend.name %>
        (<%= link_to "remove friend", user_friendship, :method => :delete %>)
        <div class="each-member">
          <div class="row">
            <div class="span1">
              <%= link_to image_tag(user_friendship.user_friend.avatar.url), user_friendship.user_friend %>
            </div>
            <div class="span1">
              <h5><%= link_to user_friendship.user_friend.name, user_friendship.user_friend %></h5>
              <% if user_friendship.user_friend.zip_code? %>
                <p>ZipCode: <%= user_friendship.user_friend.zip_code %></p>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="span12 follows">
      <h4>Accounts following you: </h4>
    </div>
    <div class="span5">

      <h4>Merchants</h4>
      <% @merchant_followers.each do |merchant_user_friendship| %>
        <div class="row">
          <div class="span5 recent-merchants-dashboard">

            <p style="margin-left:30px; margin-bottom: 0;"><%= merchant_user_friendship.merchant.bname %></p>
            <div class="each-merchant" style="margin-left:30px;">
              <div class="row">
                <div class="span1">
                  <% if merchant_user_friendship.merchant.merchant_profile && merchant_user_friendship.merchant.merchant_profile.approved %>
                    <%= link_to image_tag(merchant_user_friendship.merchant.merchant_profile.avatar.url), merchant_user_friendship.merchant %>
                  <% else %>
                    <%= link_to image_tag(merchant_user_friendship.merchant.avatar.url), merchant_user_friendship.merchant  %>
                  <% end %>
                </div>

                <div class="span1 bname">
                  <h5><%= link_to merchant_user_friendship.merchant.bname, merchant_user_friendship.merchant %></h5>
                  <p><%= merchant_user_friendship.merchant.industry %></p>
                </div>

                <div class="span2 address" >
                  <% if merchant_user_friendship.merchant.street_address %>
                    <p><%= merchant_user_friendship.merchant.street_address %></p>
                    <p><%= merchant_user_friendship.merchant.city %>, <%= merchant_user_friendship.merchant.state %> <%= merchant_user_friendship.merchant.zip_code %></p>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div class="span3 recent-users-dashboard">
      <h4>People</h4>
      <% @user_followers.each do |user_friendship| %>
         <%= user_friendship.user.name %>
        <div class="each-member">
          <div class="row">
            <div class="span1">
              <%= link_to image_tag(user_friendship.user.avatar.url), user_friendship.user %>
            </div>
            <div class="span1">
              <h5><%= link_to user_friendship.user.name, user_friendship.user %></h5>
              <% user_friendship.user.zip_code %>
                <p>ZipCode: <%= user_friendship.user.zip_code %></p>
              <% user_friendship.user.zip_code %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/dashboard/_individual_profile.html.erb
<div class="row">

  <div class="span3">
    <div class="row">
      <div class="span3">
        <h4>Name</h4>
      </div>

      <div class="span3">
        <h4>edit profile</h4>
      </div>

      <div class="span3">
        <h4>view profile</h4>
      </div>

      <div class="span3">
        <h4>Inbox</h4>
      </div>

      <div class="span3">
        <h4>My network</h4>
      </div>

      <div class="span3">
        <h4>Bitcoin address</h4>
      </div>

      <div class="span3">
        <p>New York, NY</p>
        <p>Twitter @johndoe</p> <br />
        <p>phone</p> <br />
        <p>Company</p> <br />
        <p>Category?(news and media)</p> <br />
        <p>job title</p>
      </div>
    </div>  
  </div>

  <div class="span9">
    <div class="row">
      <div class="span9">
        <h4>Discover Bitcoin Merchants</h4>
        <input type="text" placeholder="Search by category (e.g. restaurants, shopping, games)"><br />
        <input type="text" placeholder="Include your zip code to narrow results to your area"> <br />

        <button>Search</button> <br />
        <button>Map of Merchants Near Me</button>
      </div>
    </div>
    
    <div class="row">
      <div class="span6">
        <div class="row">
          <h4>Recent Bitcoin merchants listed on The Bit Pages</h4>
          <div class="span6">
            <% @recent_merchants.each do |merchant| %>
            <!-- Add Image here -->
              <h4><%= merchant.bname %></h4> <br />
              <p><%= merchant.industry %></p>
              <p><%= merchant.street_address %></p> <br />
              <p><%= merchant.city %>, <%= merchant.state %> <%= merchant.zip_code %></p>
              </p> <br />
            <% end %>
          </div>
        </div>
      </div>
    
      <div class="span3">
        <div class="row">
          <h4>New Bit Pages Members</h4>
          <% @new_members.each do |member| %>
            <!-- Add Image here -->
            <h3><%= member.name %></h3> <br />
            <!-- Mockup shows city and state; but account creation only asks for (optional) zip code -->
            <p>Zip Code: <%= member.zip_code %></p>
          <% end %>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/dashboard/_leftside_profile_merchant.html.erb
<div class="row" id="leftside-profile">
  <div class="span3">
    <h4><%= current_merchant_profile.merchant.bname %></h4>
  </div>

  <div class="span3 avatar-image-profile">
    <% if current_merchant_profile.avatar.url.present? %>
      <%= image_tag current_merchant_profile.avatar.url %>
    <% else %>
      <%= image_tag current_merchant_profile.merchant.avatar.url %>
    <% end %>
  </div>

  <div class="span3">
    <%= button_to "edit profile", edit_merchant_profile_registration_path, :method => :get, :class => "btn profile-btn" %>
  </div>

  <div class="span3">
    <%= button_to "view profile", merchant_path(current_merchant_profile.merchant) , :method => :get, :class => "btn profile-btn" %>
  </div>

  <div class="span3">
    <%= button_to "Inbox (#{current_merchant_profile.mailbox.conversations.count})", conversations_path, :method => :get, :class => "btn profile-btn"  %>
  </div>

  <div class="span3">
    <%= button_to "Connections (#{@number_of_friendships})", network_path, :method => :get, :class => "btn profile-btn" %>
  </div>

  <div>
    <img id="bitcoin-id"src="" alt="">
  </div>

  <div class="span3">
    <div style="width:170px;">
      <% if current_merchant_profile.city.present? %>
          <p style="margin-bottom:0;"><%= current_merchant_profile.city %>,</p> 
          <p><%= current_merchant_profile.state %> </p>
      <% end %>
    </div>

    <% if current_merchant_profile.twitter.present? %>
      <a href="https://twitter.com/<%= current_merchant_profile.twitter %>" class="twitter-follow-button" data-show-count="false" data-size="large"></a>
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
    <% end %>
    <p><%= current_merchant_profile.phone %></p> 
    <p><%= current_merchant_profile.company_affiliation %></p> 
    <p><%= current_merchant_profile.industry %></p> 
  </div>
</div>  

<script>
  window.onload = bitcoinCode(gon.current_user.bitcoin_address);
</script>

app/views/dashboard/_leftside_profile_user.html.erb
<div class="row" id="leftside-profile">
  <div class="span3">
    <h4><%= current_user.name %></h4>
  </div>

  <div class="span3 avatar-image-profile">
    <%= image_tag current_user.avatar.url %>
  </div>

  <div class="span3">
    <%= button_to "edit profile", edit_user_registration_path, :method => :get, :class => "btn profile-btn" %>
  </div>

  <div class="span3">
    <%= button_to "view profile", user_path(current_user) , :method => :get, :class => "btn profile-btn" %>
  </div>

  <div class="span3">
    <%= button_to "Inbox (#{current_user.mailbox.conversations.count})", conversations_path, :method => :get, :class => "btn profile-btn"  %>
  </div>

  <div class="span3">
    <% if @number_of_friendships == 0 %>
      <%= button_to "My network (0)", network_path, :method => :get, :class => "btn profile-btn" %>
    <% else %>
      <%= button_to "My network (#{@number_of_friendships})", network_path, :method => :get, :class => "btn profile-btn" %>
    <% end %>
  </div>


  <img id="bitcoin-id" src="" alt="QR code"><img>

  <div class="span3">
    <% if current_user.twitter.present? %>
      <a href="https://twitter.com/<%= current_user.twitter %>" class="twitter-follow-button" data-show-count="false" data-size="large"></a>
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
    <% end %>
    <p><%= current_user.zip_code %></p>
    <p><%= current_user.phone %></p> 
    <p><%= current_user.company_affiliation %></p> 
    <p><%= current_user.industry %></p> 
    <p><%= current_user.job_title %></p>
  </div>

</div>  

<script>
  window.onload = bitcoinCode(gon.current_user.bitcoin_address);
</script>

app/views/dashboard/_merchant_list.html.erb
<div class="span4 recent-merchants-dashboard" >
    <% @merchants.each do |merchant| %>
      <div class="each-merchant">
        <div class="row">
          <div class="span1">
            <% if merchant.merchant_profile && merchant.merchant_profile.approved %>
              <%= link_to image_tag(merchant.merchant_profile.avatar.url), merchant_path(merchant) %>
            <% else %>
              <%= link_to image_tag(merchant.avatar.url), merchant_path(merchant) %>
            <% end %>
          </div>

          <div class="span1 bname">
            <p><%= link_to merchant.bname, merchant_path(merchant) %></p>
            <p><%= merchant.industry %></p>
          </div>

          <div class="address span2" >

            <% if merchant.street_address.present? %>
              <p><%= merchant.street_address %></p>
              <p><%= merchant.city %>, <%= merchant.state %> <%= merchant.zip_code %></p>
            <% end %>

            <% if current_merchant_profile.present? %>
              <% if current_merchant_profile.merchant.merchant_friendships.include?(MerchantFriendship.where(:merchant_id => current_merchant_profile.merchant.id, :merchant_friend_id => merchant.id).first) %>              
                <b><i>Already Added!</i></b>
              <% elsif current_merchant_profile.merchant == merchant %>
                <b><i>Current User</i></b>
              <% else %>
                <%= link_to "Add to Network", merchant_friendships_path(:merchant_friend_id => merchant), :method => :post %>
              <% end %>
            <% elsif current_user.present? %>
              <% if current_user.user_merchant_friendships.include?(UserMerchantFriendship.where(:merchant_id => merchant.id, :user_id => current_user.id).first) %>
                <b><i>Already Added!</i></b>
              <% else %>
                <%= link_to "Add to Network", user_merchant_friendships_path(:merchant_id => merchant), :method => :post %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
</div>

app/views/dashboard/_nearby_merchants.html.erb
<div class="span4 nearby-merchants">
  <h4>Nearby Merchants</h4>
  <% counter = 1 %>
  <% @merchants.each do |merchant| %>
    <div class="each-merchant">
      <div class="row">

        <div class="span0 overlay">
         <h5 id="map-number"><%= counter %></h5>
        </div>

        <div class="span0 bname">
          <h5><%= link_to merchant.bname, merchant_path(merchant) %></h5>
          <p><%= merchant.industry %></p>
        </div>

        <div class="span0 address">
          <p><%= merchant.street_address %></p>
          <p><%= merchant.city %>, <%= merchant.state %> <%= merchant.zip_code %></p>
        </div>

      </div>
    </div>
    <% counter += 1 %>
  <% end %>
</div>

app/views/dashboard/_recent_members.html.erb
<div class="span3 recent-users-dashboard">
  <% @new_members.each do |member| %>
    <div class="each-member">
      <div class="row">
        <div class="span0">
          <% if member.avatar.url.present? %>
            <%= link_to image_tag(member.avatar.url), user_path(member)  %>
          <% end %>
        </div>
        <div class="span2">
          <h5><%= link_to member.name, user_path(member) %></h5>
          <% if member.zip_code.present? %>
              <p><%= member.zip_code %></p>
          <% end %>
        </div>

        <div class="span2">
          <% if current_merchant_profile.present? %>
            <% if current_merchant_profile.merchant.merchant_user_friendships.include?(MerchantUserFriendship.where(:merchant_id => current_merchant_profile.merchant.id, :user_id => member.id).first) %>
              <b><i>Already Added!</i></b>
            <% else %>
              <%= link_to "Add to Network", merchant_user_friendships_path(:merchant_id => current_merchant_profile.merchant.id, :user_id => member.id), :method => :post %>

            <% end %>
          <% elsif current_user.present? %>
            <% if current_user.user_friendships.include?(UserFriendship.where(:user_id => current_user.id, :user_friend_id => member.id).first) %>
              <b><i>Already Added!</i></b>
            <% elsif current_user == member %>
              <b><i>Current User</i></b>
            <% else %>
              <%= link_to "Add to Network", user_friendships_path(:user_id => current_user.id, :user_friend_id => member), :method => :post %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/dashboard/friendships.html.erb
<%= render "layouts/logo.html.erb" %>

<div class="row">
  <div class="span2 offset1 profile">
    <% if current_merchant.present? %>
      <%= render "leftside_profile_merchant" %>
    <% elsif current_user.present? %>
      <%= render "leftside_profile_user" %>
    <% else %>
      <%= render "leftside_profile_unregistered" %>
    <% end %>
  </div>

  <div class="span9">

    <%= render "discover_merchants" %>
    
    <div class="row">
      <div class="span6">
        <h4>Recent Bitcoin merchants listed on The Bit Pages</h4>
        <div class="row">
          <%= render "merchant_list" %>
        </div>
      </div>
    
      <%= render "recent_members" %>
    </div>
  </div>

</div>

app/views/dashboard/index.html.erb
<%= render "layouts/logo.html.erb" %>

<div class="row">
  <div class="span2 offset1 profile">
    <% if current_merchant_profile.present? %>
      <%= render "leftside_profile_merchant" %>
    <% elsif current_user.present? %>
      <%= render "leftside_profile_user" %>
    <% else %>
      <%= render "leftside_profile_unregistered" %>
    <% end %>
  </div>

  <% if flash[:alert] %>
    <div class="notice span9">
      <%= flash[:alert] %>
    </div>
  <% end %>

  <div class="span9">
    <div class="row">
      <div class="span4">
        <%= render "discover_merchants" %>
      </div>

      <div class="span4">

        <%= render "discover_users" %>
        
      </div>

    </div>

    <div class="row">
      <div class="span4">
        <h4>Recent Bitcoin merchants</h4>
        <%= will_paginate @merchants, :param_name => :merchant_page %>
        <%= render "merchant_list" %>
      </div>

      <div class="span4">
        <h4>New Bit Pages Members</h4>
        <%= will_paginate @new_members, :param_name => :user_page %>
        <%= render "recent_members" %>
      </div>
    </div>
    
    
      <div class="span6">
      </div>

    
    </div>
  </div>

</div>
 

<!-- Modal -->
<div class="modal fade" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Thank you for registering!</h4>
      </div>
      <div class="modal-body" id="incomplete-profile">
        <p>Some of your profile information has not yet been completed. Please take the time to complete your profile so we can offer you a better experience.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<script>
  
if(gon.current_user.newly_registered) {
  $("#myModal").modal();
}

</script>

app/views/dashboard/network.html.erb
<%= render "layouts/logo.html.erb" %>

<% if current_merchant_profile.present? %>
  <%= render "merchant_network" %>
<% elsif current_user.present? %>
  <%= render "individual_network" %>
<% end %>

app/views/dashboard/search.html.erb
<%= render "layouts/logo.html.erb" %>

<div class="row">
  
  <div class="span2 offset1 profile">
    <% if current_merchant_profile.present? %>
      <%= render "leftside_profile_merchant" %>
    <% elsif current_user.present?%>
      <%= render "leftside_profile_user" %>
    <% else %>
      <%= render "leftside_profile_unregistered" %>
    <% end %>
  </div>

  
  <div class="span9">
    <div class="row">
      <div class="span4">
        <%= render "discover_merchants" %>
      </div>

      <div class="span4">
        <%= render "discover_users" %>
        
      </div>

    </div>

    <div class="row">
      <div class="span4">
        <h4>Merchant search results:</h4>
        <%= render "merchant_list" %>
      </div>

      <div class="span4">
        <h4>User search results: </h4>
        <%= render "recent_members" %>
        
      </div>
    </div>
    
    
      <div class="span6">
      </div>

    
    </div>
  </div>

</div>

app/views/dashboard/unregistered_search.html.erb
<%= render "layouts/logo.html.erb" %>

<div class="row">
  
  <div class="span2 offset1 profile">
    <% if current_merchant.present? %>
      <%= render "leftside_profile_merchant" %>
    <% elsif current_user.present? %>
      <%= render "leftside_profile_user" %>
    <% else %>
      <%= render "leftside_profile_unregistered" %>
    <% end %>
  </div>

  <div class="span9">

    <div class="row">
      <div class="span5">
        <div class="span5">
          <%= render "discover_merchants" %>
        </div>

        <div class="span5">
          <h4>Search Results for Merchants: </h4>
          <div class="row merchant-list">
            <%= render "merchant_list" %>
          </div>
        </div>
      </div>


      <div class="span4 unregistered-search">
        <div class="google-map-box" id="merchant-google-map"></div>
      </div>
      
      <div class="span9">
        <%= render "recent_members" %>
      </div>
    </div>

    <div class="row">
      <div class="span4">
        
      </div>
    </div>
  </div>
  

</div>


<script>
  $(window).load(function() {
    loadScript();
  })
</script>