config/routes.rb
Bitpages::Application.routes.draw do
  
  mount Messaging::Engine => "/messaging"
  devise_for :messaging_users
  devise_for :admin_users, ActiveAdmin::Devise.config

  authenticated :user do
    root :to => "dashboard#index"
  end

  authenticated :merchant do
    root :to => "dashboard#index"
  end

  authenticated :merchant_profile do
    root :to => "dashboard#index"
  end

  root :to => "home#index"

  devise_for :merchants
  devise_for :users, :controllers => {:registrations => "user_registrations"}
  devise_for :merchant_profiles, :controllers => { :registrations => "merchant_profiles" }

  resources :profile

  resources :merchant_profiles
  
  resources :merchants
  resources :merchant_friendships
  resources :merchant_user_friendships

  resources :users
  resources :user_friendships
  resources :user_merchant_friendships

  match '/map', :to => "dashboard#map"
  match '/search', :to => "dashboard#search"
  match '/network', :to => "dashboard#network"

  match '/about', :to => "home#about"
  match '/contact', :to => "home#contact"
  match '/help', :to => "home#help"

  resources :user_submissions
  
  resources :messages

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
      delete :destroy_trash
    end
  end

  ActiveAdmin.routes(self)
    namespace :admin do
      resources :users do
        resources :messages
      end
      resources :merchant_profiles do
        resources :messages
      end
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @recent_merchants = Merchant.last(4).reverse
    @merchant_array = Merchant.where("zip_code <> ''")
    offset = rand(@merchant_array.count-1)
    gon.merchant = rand_merchant = @merchant_array.first(:offset => offset)
    gon.merchants = @merchant_array = Merchant.within(10, :origin => rand_merchant)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<h3>about page</h3>

app/views/home/contact.html.erb
<h3>contact page</h3>

app/views/home/help.html.erb
<h3>help page</h3>

app/views/home/index.html.erb
<div class="row" style="border: 1px solid black; padding: 20px;" >

<!-- !!!!!!!! -->
<!-- Left box -->
<!-- !!!!!!!! -->
  <div class="span6">
    <div class="row">
      
      <header class="span6">
        <%= render "layouts/logo.html.erb" %>
        <p>Your currency is virtual...your friends don't have to be.</p>
        
      </header>
      
      <div class="span3">
        <h3>MERCHANTS</h3>
        <p>Do you accept bitcoins as payment for goods / services? Create your page today so that customers who want to buy with bitcoins can find you!</p>
      </div>

      <div class="span3">
        <h3>INDIVIDUALS</h3>
        <p>Do you use bitcoins and need help finding merchants that accept them? Sign up today to find out who owns bitcoins - connect with other members of the bitcoin economy!</p>
      </div>

<!-- User registration and login buttons below -->
      <div class="span3 sign-in-button">
        <%= button_to "Create your Page", new_merchant_profile_registration_path, :method => :get, :class => "btn btn-warning", :html_options => {} %>
      </div>

      <div class="span3 sign-in-button">
        <%= button_to "Sign up", new_user_registration_path, :method => :get, :class => "btn btn-warning" %>
      </div>

      <div class="span6 home-login">
        <p><i>Already a member?</i></p>
        <p><%= link_to "Merchant Log In", merchant_profile_session_path, :method => :get %></p>
        <p><%= link_to "Individual Log In", user_session_path, :method => :get %></p>
      </div>
        
    </div>
  </div>

<!-- !!!!!!!! -->
<!-- Right box -->
<!-- !!!!!!!! -->
  <div class="span6">
    <div class="row">
      <div class="span6" id="right-box" >
          <% if flash[:alert] %>
            <div class="notice span5">
              <%= flash[:alert] %>
            </div>
          <% end %>

        <h4>Discover Bitcoin Merchants</h4>
        <%= form_tag map_path, :method => 'post' do %>
          <%= select_tag :category, options_for_select(Merchant::MERCHANT_CATEGORIES), :id => "unregistered-search" %>
          <%= text_field_tag :zip_code, nil, :placeholder => "Include your zip code to narrow results to your area" %> <br />
          <%= button_tag "Search", :name => "submit_search", :class => "sign-in-button btn btn-primary" %> <br>
          <%= link_to "See All Merchants", merchants_path %>
        <% end %>
        <h5>Or submit a merchant for review</h5>
        <%= button_to "Submit", user_submissions_path, :method => :get, :class => "sign-in-button btn btn-info", :style => "width: 72px;"  %>
      </div>
    </div>

    <!-- !!!!!!! -->
    <!-- Add Google map here -->
    <!-- !!!!!!! -->
    <div class="google-map-box" id="merchant-google-map">
      
    </div>
  </div>  
</div>

<div class="row merchants-list">
  <div class="span13">
    <h3 style="margin-left: -30px;">Merchants recently listed on Bit Pages</h3>
    <div class="row">
      <% @recent_merchants.each do |merchant| %>
        <div class="span recent-merchant">
            
            <div class="span2" id="box1">
              <% if merchant.merchant_profile && merchant.merchant_profile.approved %>
                <%= link_to image_tag(merchant.merchant_profile.avatar.url), merchant_path(merchant) %>
              <% else %>
                <%= link_to image_tag(merchant.avatar.url), merchant_path(merchant) %>
              <% end %>
            </div>

            <div class="span1" id="box2">
              <p>
                <%= link_to merchant.bname, merchant_path(merchant) %><br>
                <%= merchant.industry %> 
              </p>
            </div>

        </div>

      <% end %>
    </div>
  </div>
</div>

<script>
  window.onload = loadScript;
</script>