config/routes.rb
Bitpages::Application.routes.draw do
  
  mount Messaging::Engine => "/messaging"
  devise_for :messaging_users
  devise_for :admin_users, ActiveAdmin::Devise.config

  authenticated :user do
    root :to => "dashboard#index"
  end

  authenticated :merchant do
    root :to => "dashboard#index"
  end

  authenticated :merchant_profile do
    root :to => "dashboard#index"
  end

  root :to => "home#index"

  devise_for :merchants
  devise_for :users, :controllers => {:registrations => "user_registrations"}
  devise_for :merchant_profiles, :controllers => { :registrations => "merchant_profiles" }

  resources :profile

  resources :merchant_profiles
  
  resources :merchants
  resources :merchant_friendships
  resources :merchant_user_friendships

  resources :users
  resources :user_friendships
  resources :user_merchant_friendships

  match '/map', :to => "dashboard#map"
  match '/search', :to => "dashboard#search"
  match '/network', :to => "dashboard#network"

  match '/about', :to => "home#about"
  match '/contact', :to => "home#contact"
  match '/help', :to => "home#help"

  resources :user_submissions
  
  resources :messages

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
      delete :destroy_trash
    end
  end

  ActiveAdmin.routes(self)
    namespace :admin do
      resources :users do
        resources :messages
      end
      resources :merchant_profiles do
        resources :messages
      end
    end

end

app/models/merchant.rb
class Merchant < ActiveRecord::Base
  scope :alphabetically, order("bname ASC")
  scope :latest, order("created_at DESC")
  
  devise :database_authenticatable,
         :rememberable, :trackable,
         :authentication_keys => [:bname]

  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :bname, :avatar, :avatar_cache, :remove_avatar, :bio, :street_address, :city, :state, :zip_code, :online_business, :bitcoin_address, :company_website, :phone, :company_affiliation, :industry, :twitter

  mount_uploader :avatar, AvatarUploader
  
  geocoded_by :geocode_method
  
  after_validation :geocode

  acts_as_mappable :lat_column_name => :latitude,
                   :lng_column_name => :longitude

  has_many :merchant_friendships, :dependent => :destroy
  has_many :merchant_friends, :through => :merchant_friendships

  has_many :merchant_user_friendships, :dependent => :destroy
  has_many :users, :through => :merchant_user_friendships

  has_one :merchant_profile, :dependent => :destroy

  MERCHANT_CATEGORIES = ["", "Athletics", "Arts \& Entertainment", "Automotive", "Beauty \& Spas", "Education", "Event Planning \& Services", "Financial Services", "Food", "Health \& Medical", "Home Services", "Hotels \& Travel", "Media", "Nightlife", "Pets", "Professional Services", "Public Services \& Government", "Real Estate", "Religious Organizations", "Restaurants", "Shopping", "Other"]

  def geocode_method
    "#{self.street_address} #{self.city} #{self.state} #{self.zip_code}"
  end

  def self.number_of_friendships(merchant)
    this_merchant_follow_other_merchants = MerchantFriendship.where(:merchant_id => merchant.id)
    other_merchants_follow_this_merchant = MerchantFriendship.where(:merchant_friend_id => merchant.id)

    this_merchant_follow_other_users = MerchantUserFriendship.where(:merchant_id => merchant.id)
    other_users_follow_this_merchant = UserMerchantFriendship.where(:merchant_id => merchant.id)

    total = this_merchant_follow_other_merchants.count + other_merchants_follow_this_merchant.count + this_merchant_follow_other_users.count + other_users_follow_this_merchant.count
    return total
  end
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  def index
    @merchants = Merchant.alphabetically.paginate(:page => params[:merchant_page], :per_page => 10)
  end

  def show
    begin
      @merchant = Merchant.find(params[:id])
      @number_of_friendships = Merchant.number_of_friendships(@merchant)
      gon.merchants = @merchants = [@merchant]
      gon.merchant = @merchant
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "That page doesn't exist!"
      redirect_to root_url
    end
  end

  def profile
    @merchant = current_merchant
    gon.merchant = @merchant
  end

  def update
  end
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/views/merchants/_merchant_profile.html.erb
<div class="row">
  <div class="span5">
    <div class="row profile">
      <div class="offset1 span4">

        <h4><%= @merchant.bname %></h4>
        <%= image_tag(@merchant.avatar.url) %>
        <img id="bitcoin-id" src="" alt="QR code"><img>
      </div>

      <div class="offset1 span5">
        <p><%= @merchant.industry %></p>
      </div>

      <div class="offset1 span5">
        <% if !@merchant.online_business %>
          <% if @merchant.city.present? %>
            <p><%= @merchant.street_address %></p>
            <p><%= @merchant.city %>, <%= @merchant.state %> <%= @merchant.zip_code %></p>
          <% end %>
        <% else %>
          <p>Online Business</p>
        <% end %>
        <p><%=link_to @merchant.company_website, @merchant.company_website %></p>
        <% if @merchant.twitter.present? %>
          <a href="https://twitter.com/<%= @merchant.twitter %>" class="twitter-follow-button" data-show-count="false">Follow <%= @merchant.twitter %></a>
          <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
        <% end %>
        <p><%= @merchant.phone %></p><br><br><br>
        <p>Network count: <%= @number_of_friendships %></p>
      </div>
    </div>  
  </div>

  <div class="span7">
    <div class="row">
      <div class="claimed-merchant">

        <% if @merchant.merchant_profile.present? && @merchant.merchant_profile.approved %>
          <div class="span3">
          <% if current_merchant_profile.present? %>
            <% if current_merchant_profile.merchant.merchant_friendships.include?(MerchantFriendship.where(:merchant_friend_id => @merchant.id, :merchant_id => current_merchant_profile.merchant.id).first) %>
              <b><i>Already Added!</i></b>
            <% else %>
              <%= button_to "Add to Network", merchant_friendships_path(:merchant_friend_id => @merchant), :method => :post %>
            <% end %>
          <% elsif current_user.present? %>
            <% if current_user.user_merchant_friendships.include?(UserMerchantFriendship.where(:merchant_id => @merchant.id, :user_id => current_user.id).first) %>
              <b><i>Already Added!</i></b>
            <% else %>
              <%= button_to "Add to Network", user_merchant_friendships_path(:merchant_id => @merchant.id), :method => :post %>
            <% end %>
          <% end %>
          
          <p><%= @merchant.bio %></p>
          </div>
          <div class="span3 offset1">
            <button>Send a message</button>
            <%= link_to "Send Message", :controller => "conversations", :action => "new", :email => @user.email%>
          </div>

        <% elsif @merchant.merchant_profile.present? && @merchant.merchant_profile.approved==false %>
          <div class="merchant-profile-approval">
            <h4>This page is pending approval. If you are the business owner, thank you for claiming your account. We will contact you soon!</h4>
            <p>In the meantime, you can log into your account and edit your merchant profile information</p>
            <%= link_to "Sign in", new_merchant_profile_session_path %>
          </div>

        <% else %>
          <div class="merchant-profile-approval">
            <h3>Is this your business?</h3>
            <%= link_to "CLAIM THIS PAGE", new_merchant_profile_registration_path(:merchant => {
                  :id => @merchant.id, 
                  :bname => @merchant.bname, 
                  :street_address => @merchant.street_address,
                  :state => @merchant.state,
                  :city => @merchant.city,
                  :zip_code => @merchant.zip_code
                }) %>


            <p>Creating a Bit Pages account will allow you to add information about your business so that Bitcoin users can easily find you ... use their Bitcoins to pay for goods & services that you offer.</p>
          </div>
        <% end %>
        
      </div>
      

    </div>


    <!-- Google Maps -->
    <%= render "layouts/google_map.html.erb" %>

  </div>
</div>

<!-- Load Google Maps Below -->
<script>
  $(window).load(function() {
    bitcoinCode(gon.merchant.bitcoin_address);
    loadScript();
  })
</script>

app/views/merchants/index.html.erb
<%= render "layouts/logo.html.erb" %>

<div class="all-merchants">
  <p>Listed Merchants on Bitpages</p>
</div>
<div class="offset1">
  
  <div class="span4 recent-merchants-dashboard" >
    <%= will_paginate @merchants, :param_name => :merchant_page %>
    <%= render "dashboard/merchant_list.html.erb" %>
  </div>
</div>

app/views/merchants/profile.html.erb
<h1>Bit Pages Logo (Profile)</h1>
<hr style="width: 100%; height: 1em; background: #fff; margin: 0 auto;">


<%= render "merchant_profile" %>

app/views/merchants/show.html.erb
<%= render "layouts/logo.html.erb" %>

<% if @merchant.merchant_profile.present? && @merchant.merchant_profile.approved == true %>
  <%= render "merchant_profiles/merchant_profile_profile.html.erb" %>
<% else %>
  <%= render "merchant_profile" %>
<% end %>

app/views/merchants/update.html.erb
<h1>Merchants#update</h1>
<p>Find me in app/views/merchants/update.html.erb</p>