config/routes.rb
Bitpages::Application.routes.draw do
  
  mount Messaging::Engine => "/messaging"
  devise_for :messaging_users
  devise_for :admin_users, ActiveAdmin::Devise.config

  authenticated :user do
    root :to => "dashboard#index"
  end

  authenticated :merchant do
    root :to => "dashboard#index"
  end

  authenticated :merchant_profile do
    root :to => "dashboard#index"
  end

  root :to => "home#index"

  devise_for :merchants
  devise_for :users, :controllers => {:registrations => "user_registrations"}
  devise_for :merchant_profiles, :controllers => { :registrations => "merchant_profiles" }

  resources :profile

  resources :merchant_profiles
  
  resources :merchants
  resources :merchant_friendships
  resources :merchant_user_friendships

  resources :users
  resources :user_friendships
  resources :user_merchant_friendships

  match '/map', :to => "dashboard#map"
  match '/search', :to => "dashboard#search"
  match '/network', :to => "dashboard#network"

  match '/about', :to => "home#about"
  match '/contact', :to => "home#contact"
  match '/help', :to => "home#help"

  resources :user_submissions
  
  resources :messages

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
      delete :destroy_trash
    end
  end

  ActiveAdmin.routes(self)
    namespace :admin do
      resources :users do
        resources :messages
      end
      resources :merchant_profiles do
        resources :messages
      end
    end

end

app/views/layouts/_google_map.html.erb
<% unless @merchants.first.street_address.blank? && @merchants.first.zip_code.blank? && @merchants.first.city.blank? %>
  <div id="merchant-google-map" class="google-map-box"></div>
<% else %>    
  <h3><i>This business has not yet added an address.</i></h3>
<% end %>

app/views/layouts/_logo.html.erb
<%= link_to image_tag("bitpages_logo.png"), root_url %>
<hr style="width: 100%; height: 1em; background: #fff; margin: 0 auto;">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Bitpages</title>
  <%= include_gon %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="user_nav">
    <% if current_merchant.class == Merchant %>
      <% if merchant_signed_in? %>
        Signed in as <%= current_merchant.email %>. Not you?
        <%= link_to "Sign out - Merchant", destroy_merchant_session_path, :method => "delete" %>
      <% else %>
        <%= link_to "Sign up", new_merchant_registration_path %> or
        <%= link_to "Sign in", new_merchant_session_path %>
      <% end %>
    <% elsif current_user.class == User %>
      <% if user_signed_in? %>
        Signed in as <%= current_user.email %>. Not you?
        <%= link_to "Sign out - Individual", destroy_user_session_path, :method => "delete" %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path %> or
        <%= link_to "Sign in", new_user_session_path %>
      <% end %>
    <% elsif current_merchant_profile.class == MerchantProfile %>
      <% if merchant_profile_signed_in? %>
        Signed in as <%= current_merchant_profile.email %>. Not you?
        <%= link_to "Sign out - Merchant Profile", destroy_merchant_profile_session_path, :method => "delete" %>
      <% end %>
    <% end %>
  </div>
  
  <%= yield %>


  <footer>
    <hr style="width: 75%; height: 1em; background: #fff; margin: 0 auto;">
    <p>Need Help? Contact: <a href="mailto:ben@thebitpages.com">ben@thebitpages.com</a></p>
  </footer>
  
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-43185453-1', 'thebitpages.com');
    ga('send', 'pageview');
  </script>

</body>
</html>